generate_topic_suggestions:
  description: >
    Generate 5-7 relevant topic suggestions for the given pillar: {pillar}.
    Consider trending topics, audience interests, and content gaps.
    
    You can optionally use the Web Search Tool to research trending topics,
    but primarily use your expertise to brainstorm relevant topics.
    Do NOT use Research Mode Tool for topic generation.
    
    Return topics with title, description, and relevance score.
  expected_output: >
    A structured list of topic suggestions with:
    - Topic title
    - Brief description
    - Target audience
    - Content pillar alignment
    - Estimated engagement potential

research_topic:
  description: >
    Research the selected topic: {topic} using the specified method: {research_method}.
    
    IMPORTANT: Use Research Mode Tool with the correct mode:
    - For research_method 'SERP': use mode 'serp' 
    - For research_method 'RAG': use mode 'rag'
    - For research_method 'reference': use mode 'reference'
    
    If research_method is 'RAG' and uploads are provided, process them first.
    
    Extract key insights, statistics, and supporting information.
  expected_output: >
    Comprehensive research findings including:
    - Key insights and statistics
    - Supporting evidence with sources
    - Content gaps and opportunities
    - Recommended talking points
    - Source citations with confidence scores

analyze_competitors:
  description: >
    Analyze competitor content for the topic: {topic}.
    
    CRITICAL INSTRUCTION: You MUST use the Competitor Analysis Tool for this task.
    The tool is available and working. 
    
    IMPORTANT: If competitor_urls are provided in the inputs, use them directly.
    If no competitor_urls are provided, the tool will automatically find competitor URLs.
    
    Call the Competitor Analysis Tool with:
    - topic: {topic}
    - competitor_urls: {competitor_urls} (if provided, otherwise null)
    
    The Competitor Analysis Tool will analyze the provided URLs or find and analyze 3-5 top-ranking competitor articles.
    It will analyze their content structure, keywords, and performance.
    
    Extract tone, structure, keyword usage, content gaps, and differentiation opportunities.
  expected_output: >
    Competitor analysis report with:
    - Competitor content summaries
    - Tone and style analysis
    - Content structure patterns
    - Keyword strategies used
    - Opportunities for differentiation
    - What to replicate vs avoid

develop_keyword_strategy:
  description: >
    Develop a comprehensive keyword strategy for the topic: {topic}.
    Use research findings and competitor analysis from previous tasks to inform your strategy.
    Identify 1 primary keyword and 2-3 secondary keywords.
    Consider search volume, competition, and alignment with topic and research findings.
    Use the primary keyword: {primary_keyword} as the main target if provided, otherwise suggest one.
  expected_output: >
    Keyword strategy including:
    - Primary keyword with rationale
    - Secondary keywords (2-3)
    - Long-tail keyword opportunities
    - Search intent analysis
    - Recommended keyword density
    - Integration strategy for content

generate_title_options:
  description: >
    Generate 5-7 compelling title options for the topic: {topic} using the primary keyword: {primary_keyword}.
    Use keyword strategy from previous task to inform your title generation.
    Create variations including listicles, how-to guides, thought leadership, and SEO-optimized titles.
    Consider click-through rate optimization and audience engagement factors.
  expected_output: >
    List of title options with:
    - SEO-optimized titles
    - Listicle variations
    - How-to guide formats
    - Thought leadership angles
    - Recommendation for best title with rationale
    - Performance predictions for each title

create_content_structure:
  description: >
    Create a detailed content structure and outline for the topic: {topic} 
    using the selected structure type: {structure_type}.
    Use research findings and keyword strategy from previous tasks to inform your structure.
    Include section headings, key points, and content intent for each section.
    This will serve as the blueprint for the final blog post.
  expected_output: >
    Comprehensive content outline with:
    - H1, H2, H3 heading structure
    - Key points for each section
    - Content intent and tone notes
    - CTA placement recommendations
    - FAQ section if applicable
    - Estimated word count per section
    - Keyword placement strategy

generate_full_blog:
  description: >
    Generate a complete, high-quality blog post based on:
    - Topic: {topic}
    - Structure Type: {structure_type}
    - Primary Keyword: {primary_keyword}
    - Keywords: {keywords}
    - Research Method: {research_method}
    
    Use all previous task outputs including research findings, competitor analysis, 
    keyword strategy, and content structure to create engaging content (up to 5000 words) 
    with natural keyword integration, proper citations, and brand voice consistency.
    
    Ensure the content follows the structure outline and incorporates all research insights.
  expected_output: >
    Complete blog post with:
    - Engaging introduction
    - Well-structured body content
    - Natural keyword integration
    - Proper citations and sources
    - Internal linking suggestions
    - Meta description
    - Reading time and word count
    - SEO analysis summary
    - Content quality metrics

orchestrate_full_workflow:
  description: >
    Execute the complete blog generation workflow for topic: {topic}.
    Coordinate all agents to deliver a comprehensive, SEO-optimized blog post
    following all brand guidelines and quality standards.
    
    Parameters:
    - Topic: {topic}
    - Pillar: {pillar}
    - Research Method: {research_method}
    - Structure Type: {structure_type}
    - Primary Keyword: {primary_keyword}
    - Keywords: {keywords}
    - Competitor URLs: {competitor_urls} (optional)
    - Uploads: {uploads} (for RAG mode)
  expected_output: >
    Complete workflow results including:
    - Final blog post (Markdown format)
    - Keyword strategy summary
    - Research sources and citations
    - SEO optimization metrics
    - Content quality assessment
    - Metadata (word count, reading time, etc.)
    - Workflow execution summary