generate_topic_suggestions:
  description: >
    Generate 5-7 relevant topic suggestions for the given pillar: {pillar}.
    Consider trending topics, audience interests, and content gaps.
    Return topics with title, description, and relevance score.
  expected_output: >
    A structured list of topic suggestions with:
    - Topic title
    - Brief description
    - Target audience
    - Content pillar alignment
    - Estimated engagement potential
  agent: topic_researcher

research_topic:
  description: >
    Research the selected topic: {topic} using the specified method: {research_method}.
    For SERP analysis: search and analyze top 10 search results.
    For Internal KB: retrieve relevant documents from knowledge base.
    For Upload: process and analyze uploaded reference materials.
    Extract key insights, statistics, and supporting information.
  expected_output: >
    Comprehensive research findings including:
    - Key insights and statistics
    - Supporting evidence with sources
    - Content gaps and opportunities
    - Recommended talking points
    - Source citations with confidence scores
  agent: knowledge_retriever

analyze_competitors:
  description: >
    Analyze competitor content for the topic: {topic}.
    Find and analyze 3-5 top-ranking competitor articles.
    Extract tone, structure, keyword usage, content gaps, and differentiation opportunities.
  expected_output: >
    Competitor analysis report with:
    - Competitor content summaries
    - Tone and style analysis
    - Content structure patterns
    - Keyword strategies used
    - Opportunities for differentiation
    - What to replicate vs avoid
  agent: competitor_analyst

develop_keyword_strategy:
  description: >
    Develop a comprehensive keyword strategy for the topic: {topic}.
    Identify 1 primary keyword and 2-3 secondary keywords.
    Consider search volume, competition, and alignment with topic and research findings.
  expected_output: >
    Keyword strategy including:
    - Primary keyword with rationale
    - Secondary keywords (2-3)
    - Long-tail keyword opportunities
    - Search intent analysis
    - Recommended keyword density
  agent: seo_strategist

generate_title_options:
  description: >
    Generate 5-7 compelling title options for the topic: {topic} using the primary keyword: {primary_keyword}.
    Create variations including listicles, how-to guides, thought leadership, and SEO-optimized titles.
  expected_output: >
    List of title options with:
    - SEO-optimized titles
    - Listicle variations
    - How-to guide formats
    - Thought leadership angles
    - Recommendation for best title with rationale
  agent: content_structurer

create_content_structure:
  description: >
    Create a detailed content structure and outline for the topic: {topic} 
    using the selected structure type: {structure_type}.
    Include section headings, key points, and content intent for each section.
  expected_output: >
    Comprehensive content outline with:
    - H1, H2, H3 heading structure
    - Key points for each section
    - Content intent and tone notes
    - CTA placement recommendations
    - FAQ section if applicable
    - Estimated word count per section
  agent: content_structurer

generate_full_blog:
  description: >
    Generate a complete, high-quality blog post based on:
    - Topic: {topic}
    - Outline: {outline}
    - Keywords: {keywords}
    - Research findings: {research_findings}
    - Brand voice guidelines
    
    Create engaging content (up to 5000 words) with natural keyword integration,
    proper citations, and brand voice consistency.
  expected_output: >
    Complete blog post with:
    - Engaging introduction
    - Well-structured body content
    - Natural keyword integration
    - Proper citations and sources
    - Internal linking suggestions
    - Meta description
    - Reading time and word count
    - SEO analysis summary
  agent: blog_writer

orchestrate_full_workflow:
  description: >
    Execute the complete blog generation workflow for topic: {topic}.
    Coordinate all agents to deliver a comprehensive, SEO-optimized blog post
    following all brand guidelines and quality standards.
  expected_output: >
    Complete workflow results including:
    - Final blog post (Markdown format)
    - Keyword strategy summary
    - Research sources and citations
    - SEO optimization metrics
    - Content quality assessment
    - Metadata (word count, reading time, etc.)
  agent: blog_writer